target: all
search_enabled: true

server:
  http_listen_port: 3200

query_frontend:
  search:
    query_backend_after: 1s # setting these both to 0 will force all range searches to hit the backend
    query_ingesters_until: 1s

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 1s
  max_block_bytes: 1
  max_block_duration: 2s
  complete_block_timeout: 1s
  flush_check_period: 1s

storage:
  trace:
    backend: local
    local:
      path: /var/tempo
    blocklist_poll: 5s
    pool:
      max_workers: 10
      queue_depth: 100
    block:
      version: vParquet

overrides:
  max_search_bytes_per_trace: 50_000
